#!/bin/bash

# remove previous build
rm -fr yse_binary_release_linux

# create directories
echo '-> creating directories...'
mkdir yse_binary_release_linux
mkdir yse_binary_release_linux/include
mkdir yse_binary_release_linux/lib
mkdir yse_binary_release_linux/demo
mkdir yse_binary_release_linux/demo/compiled

# create static library
echo '-> creating static library...' 
cd static_library/Builds/LinuxMakefile/
make CONFIG=Release

cd ../../../
mv static_library/Builds/LinuxMakefile/build/libyse_static.a yse_binary_release_linux/lib/libyse.a

#create dynamic library
echo '-> creating dynamic library...' 
cd dll/Builds/Linux/
make CONFIG=Release

cd ../../../
mv dll/Builds/Linux/build/libyse.a yse_binary_release_linux/lib/libyse.so

# copy include files
echo '-> copying header files...' 
cp -fr include/* yse_binary_release_linux/include/

# copy demo source
echo '-> copying demo source...'
cp -fr ConsoleDemo/source yse_binary_release_linux/demo
cp -fr scripts/generateDemoLinux yse_binary_release_linux/demo
cp -fr bin/*.ogg yse_binary_release_linux/demo/compiled
cp -fr bin/*.wav yse_binary_release_linux/demo/compiled
cp -fr bin/*.env yse_binary_release_linux/demo/compiled

# compile demo
read -n 1 -p "compile and test demo apps? (y/n) " answer
case ${answer:0:1} in
  y|Y )
    echo '-> compiling demos. Please verify them.'
    cd yse_binary_release_linux/demo/
    ./generateDemoLinux

    cd ../../
    echo -e '\n-> removing binaries...'
    for entry in `ls yse_binary_release_linux/demo/compiled/demo*`; do
      rm $entry
    done
  ;;
esac

# add info files
echo -e "\n-> adding info files..."
cp AUTHORS yse_binary_release_linux
cp COPYING yse_binary_release_linux
cp README yse_binary_release_linux

