/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_Yse_WRAP_H_
#define SWIG_Yse_WRAP_H_

class SwigDirector_logHandler : public YSE::logHandler, public Swig::Director {

public:
    SwigDirector_logHandler();
    virtual void AddMessage(std::string const &message);
    virtual ~SwigDirector_logHandler();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(char *);
    void swig_connect_director(SWIG_Callback0_t callbackAddMessage);

private:
    SWIG_Callback0_t swig_callbackAddMessage;
    void swig_init_callbacks();
};


#endif
