#include "gNext.h"
#include "../pObjectList.hpp"
#include <cstdint>
#include <string>

using namespace YSE::PATCHER;

#define className gNext

CONSTRUCT() {
  // One inlet. Max gives bang, int and float the description "Performs the same
  // as anything", and anything is the method that runs the test, so all four
  // message kinds arrive at the same place and the payload never matters.
  ADD_IN_0;
  REG_BANG_IN(SetBang);
  REG_INT_IN(SetInt);
  REG_FLOAT_IN(SetFloat);
  REG_LIST_IN(SetList);

  // Max, under Output: "Out left outlet: A bang is sent out if the current
  // message is not part of the same logical event as the previously received
  // message. Out right outlet: A bang is sent out if the current message is
  // part of the same logical event as the previously received message." Two
  // halves of one test, so exactly one of them fires per message.
  ADD_OUT_BANG;
  ADD_OUT_BANG;

  // No parameters at all. Max: "Arguments: None." There is no state a creation
  // argument could pre-declare — the object's memory is the previous message's
  // event, and an event that has not happened cannot be named.

  ADD_DESCRIPTION(
      "Bangs the left outlet for the first message of a burst and the right outlet for every "
      "message after it — Max's next, whose summary line is 'Detect separation of messages'. The "
      "use Max names is the one to keep in mind: 'next is useful for doing something once per dump "
      "of an object such as coll'. A dump sprays a hundred messages down one cord, and .next marks "
      "the first of them and labels the other ninety-nine, so a patch can open a file, reset a "
      "counter or start an envelope once per dump rather than a hundred times, without knowing how "
      "long the dump is. The name invites the wrong reading and the wrong reading is a different "
      "object: this measures no interval, holds no clock and has no threshold. Two messages a "
      "microsecond apart are the same event if one caused the other, and two messages a "
      "microsecond "
      "apart are different events if they came from two stimuli. Max spells it out — 'a logical "
      "event is one of the following: a mouse click, the ongoing polling of a mouse drag, an event "
      "generated by the scheduler (such as the bang from a metro), a MIDI event, or a keyboard "
      "event [...] if you click on a bang twice, the two bangs are not part of the same logical "
      "event, but if you put bang, bang in a message box, or use the uzi object to send out two "
      "bangs in a row, these bangs are part of the same logical event'. Two clicks are two events "
      "however fast you click, and two bangs from one message box are one event however slow the "
      "patch is, so an elapsed-time implementation gets both cases backwards. This patcher has no "
      "scheduler to take ticks from, but it has the structure Max's definition rests on: message "
      "delivery is synchronous and depth-first, so everything one stimulus causes runs inside the "
      "call frame of the dispatch that started it. Counting that nesting reproduces Max's grouping "
      "case for case — two host calls are two events, two .metro ticks are two events, and a "
      ".trigger's whole right-to-left fan-out is one event, which makes '.trigger b b' into a "
      ".next "
      "this patcher's 'bang, bang' message box: first bang left, second bang right. The very first "
      "message an object ever receives goes out the left outlet, there being no previous message "
      "for it to share an event with, which is what lets a patch read that outlet as 'a new burst "
      "starts here' and be right about the first burst too. Exactly one outlet fires per message, "
      "always: the two are a complete partition of the inlet's traffic, so nothing is swallowed "
      "and "
      "the right outlet is worth wiring as 'and here is the rest of the burst'. Because only one "
      "fires there is no right-to-left order to respect, unlike .trigger, .bangbang, .mean or "
      ".peak. Everything is a bang — Max gives bang, int and float the description 'Performs the "
      "same as anything', so the payload is documented as irrelevant and a 0 separates like any "
      "other message. There are no creation arguments and no messages, as Max lists neither: there "
      "is no state a reset could return the object to, and in an object where every symbol is an "
      "ordinary tested message, each word learned would be a message that stopped being tested. "
      "Calculate() does nothing, since an emitting one would fire the object once per DSP block "
      "from a stimulus no patch sent.");
  ADD_CATEGORY(pCategory::GENERIC);
  INLET_DOC(0, "in",
            "Bang, int, float or list — whatever arrives is discarded and only its timing in the "
            "message graph is read. A bang leaves outlet 0 if this message did not arrive as part "
            "of the same stimulus as the previous one, and outlet 1 if it did. The first message "
            "after the object is created always leaves outlet 0. Takes no messages: every word is "
            "an ordinary tested message, as in Max.",
            "any");
  OUTLET_DOC(0, "separated",
             "A bang, when this message starts a new logical event — a fresh host call, GUI "
             "action or .metro tick, rather than more of the fan-out that is already running. Wire "
             "it to do something once per burst.",
             "bang");
  OUTLET_DOC(1, "same",
             "A bang, when this message belongs to the same logical event as the previous one — "
             "the second and later messages of one .trigger fan-out, dump or chain. Wire it to "
             "handle the rest of the burst; leave it unconnected to get a plain once-per-burst "
             "trigger.",
             "bang");
}

void gNext::Test(YSE::THREAD thread) {
  // The dispatch layer's answer to "which stimulus is being delivered right
  // now". Opaque and unique: it is only ever compared, never interpreted.
  const std::uint64_t event = CurrentMessageEvent();

  // Three conditions, and each one is load-bearing:
  //
  //  - `seen`: the first message ever has no previous message to share an event
  //    with, so it is separated. Max compares against "a previous message".
  //  - `event != 0`: 0 means no dispatch is in progress, which happens when a
  //    handler is called directly rather than through the inlet. Two such calls
  //    are two stimuli that happen to carry the same non-id, and folding them
  //    together would report a burst that never existed.
  //  - `event == lastEvent`: the actual test.
  const bool same = seen && event != 0 && event == lastEvent;

  // Settled before the send, as .onebang and .togedge settle theirs. The send
  // path is synchronous with no queue in between, so a patch that loops an
  // outlet back into this inlet re-enters here inside the SendBang below; with
  // the stores after the send it would find the object still describing the
  // previous message and report the loop as a fresh event every time.
  lastEvent = event;
  seen = true;
  separated = !same;

  // Max: exactly the two halves of one test, so one outlet and only one.
  outputs[same ? 1 : 0].SendBang(thread);
}

BANG_IN(SetBang) {
  if (inlet != 0) return;
  Test(thread);
}

INT_IN(SetInt) {
  // Max: "Performs the same as anything." The value is discarded, including a
  // 0 — nothing this object emits could carry it.
  (void)value;
  SetBang(inlet, thread);
}

FLOAT_IN(SetFloat) {
  (void)value;
  SetBang(inlet, thread);
}

LIST_IN(SetList) {
  // Max's `anything`, which is where the test lives. The text is never read:
  // there is no word this object knows, and no content that could change the
  // answer, so there is nothing to parse and nothing to allocate.
  (void)value;
  SetBang(inlet, thread);
}

GUI_VALUE() {
  // Which outlet the last message left by — the only thing an editor could
  // usefully show, and the only thing about this object a patch can observe
  // without wiring both outlets.
  return separated ? "1" : "0";
}
