#pragma once
#include "../pObject.h"
#include <cstdint>
#include <string>

namespace YSE {
  namespace PATCHER {

    /**
     *  @brief Tell the first message of a burst from the rest of it —
     *         ``.next`` (issue #471).
     *
     *  Max's ``next``, whose one-line summary is "Detect separation of
     *  messages". A message that is not part of the same *event* as the
     *  previous one bangs the left outlet; one that is part of the same event
     *  bangs the right outlet. Max: "Sends a bang out its left outlet when an
     *  incoming message is not part of the same Max 'event' as a previous
     *  message. (An 'event' is a mouse click, key press, MIDI event, or tick of
     *  the scheduler.) Otherwise, next sends a bang out its right outlet."
     *
     *  The use Max names is the one to keep in mind: "``next`` is useful for
     *  doing something once per dump of an object such as ``coll``." A dump
     *  sprays a hundred messages down one cord; ``.next`` marks the first of
     *  them and labels the other ninety-nine, so a patch can open a file, reset
     *  a counter or start an envelope *once per dump* rather than a hundred
     *  times, without knowing how long the dump is.
     *
     *  ### Separation in the message stream, not separation in time
     *
     *  The title of this object invites the wrong reading, and the wrong
     *  reading is a different object. ``.next`` measures no interval, holds no
     *  clock and has no threshold: two messages a microsecond apart are the
     *  *same* event if one caused the other, and two messages a microsecond
     *  apart are *different* events if they came from two stimuli. Max spells
     *  this out under ``anything``:
     *
     *  > A logical event is one of the following: a mouse click, the ongoing
     *  > polling of a mouse drag, an event generated by the scheduler (such as
     *  > the bang from a metro), a MIDI event, or a keyboard event. [...] if
     *  > you click on a bang twice, the two bangs are not part of the same
     *  > logical event. But if you put ``bang, bang`` in a message box, or use
     *  > the ``uzi`` object to send out two bangs in a row, these bangs are
     *  > part of the same logical event.
     *
     *  Two clicks are two events *however fast you click*, and the two bangs
     *  from one message box are one event *however slow the patch is*. An
     *  elapsed-time implementation gets both of those backwards, and it would
     *  also be untestable without sleeping and unreliable under load — the
     *  three reasons a timer was never on the table here.
     *
     *  ### What an "event" is in this patcher
     *
     *  There is no scheduler here to take ticks from, but the structure Max's
     *  definition depends on is present: message delivery is synchronous and
     *  depth-first, so everything one stimulus causes runs inside the call
     *  frame of the dispatch that started it. ``CurrentMessageEvent()`` (see
     *  ``inlet.h``) counts that nesting and hands out one id per outermost
     *  dispatch, which reproduces Max's grouping case for case:
     *
     *  | stimulus                              | events |
     *  |---------------------------------------|--------|
     *  | two host calls / two GUI actions      | two    |
     *  | two ``.metro`` ticks                  | two    |
     *  | ``.trigger b b`` fanning out to both  | one    |
     *  | a chain of boxes, however long        | one    |
     *
     *  So ``.trigger b b`` into a ``.next`` is this patcher's ``bang, bang``
     *  message box: the first bang leaves the left outlet, the second the
     *  right. That is the whole object, and it is why the mechanism lives in
     *  the dispatch layer rather than in this class — nothing an object can see
     *  about a single message distinguishes the second bang of a burst from the
     *  first message of the next one.
     *
     *  ### The first message ever
     *
     *  Goes out the left outlet. There is no previous message for it to be
     *  "part of the same event as", and Max's wording is a comparison against
     *  "a previous message" rather than against a stored event. A patch reading
     *  the left outlet as "a new burst starts here" gets the right answer on
     *  the very first burst, which is the reading the ``coll``-dump use
     *  depends on.
     *
     *  ### Exactly one outlet fires, always
     *
     *  Every message accepted produces exactly one bang. The two outlets are a
     *  complete partition of the inlet's traffic — Max documents both under
     *  Output as the two halves of one test — so nothing is ever swallowed and
     *  the right outlet is worth wiring: it is "and here is the rest of the
     *  burst". Because only one fires, there is no firing order to respect,
     *  unlike ``.trigger``, ``.bangbang``, ``.mean`` or ``.peak``.
     *
     *  ### Everything is a bang
     *
     *  Max gives ``bang``, ``int`` and ``float`` the description "Performs the
     *  same as anything", and ``anything`` is the method that does the test.
     *  The payload is not merely unused, it is documented as irrelevant: what
     *  comes out carries no value, so there is nothing an input value could
     *  turn into. A 0 is a message like any other and separates like any other.
     *
     *  There are no messages and no creation arguments — Max lists none of
     *  either, and there is no state a ``reset`` could usefully return the
     *  object to. Anything that is not a number is Max's ``anything``, so every
     *  word this object might learn would be a message it stopped testing; the
     *  same argument ``.onebang`` (#470) makes for keeping its vocabulary to
     *  one word applies here for keeping it to none.
     *
     *  ### Real-time behaviour
     *
     *  ``Calculate()`` does nothing. The object is driven by its inlet, and an
     *  emitting Calculate() would fire the object once per DSP block from a
     *  stimulus no patch sent.
     *
     *  Nothing on any path allocates, locks or blocks: a message is one
     *  thread-local load, two comparisons, two plain stores and one
     *  ``SendBang``. The object holds no container and reads no text — a list
     *  is never parsed, since its content cannot change the answer.
     *
     *  The state is settled before the send, as ``.onebang`` and ``.togedge``
     *  settle theirs, because the send path is synchronous and re-entrant: a
     *  patch that loops an outlet back into this inlet re-enters here *inside*
     *  the ``SendBang``, and must find the object already describing the
     *  message that is being reported rather than the one before it.
     */
    PATCHER_CLASS(gNext, YSE::OBJ::G_NEXT)
    _NO_MESSAGES
    _NO_CALCULATE

    _BANG_IN(SetBang)
    _INT_IN(SetInt)
    _FLOAT_IN(SetFloat)
    _LIST_IN(SetList)

    _HAS_GUI

    /**
     *  @brief Whether any message has reached the inlet yet.
     *
     *  Exposed because the object's answer to the very first message is a
     *  documented special case ("there is no previous message"), and after one
     *  message "the object is fresh" and "the last message was separated" stop
     *  being the same question.
     */
    bool HasSeenMessage() const {
      return seen;
    }

    /**
     *  @brief Which outlet the last message left by — true for the left
     *         (separated) outlet.
     *
     *  The object's whole observable state, and the value the GUI reports.
     *  True before any message has arrived, since the next one will be
     *  separated.
     */
    bool LastWasSeparated() const {
      return separated;
    }

  private:
    // A message reached the inlet. Test it against the previous one and bang
    // one of the two outlets. The only path that emits.
    void Test(YSE::THREAD thread);

    // The event the previous message belonged to, or 0 when there was none.
    // Compared, never interpreted; ids are opaque and unique.
    std::uint64_t lastEvent = 0;

    // Whether `lastEvent` describes a real message. Separate from a 0 id
    // because 0 also means "dispatched outside any inlet", and the two must not
    // collapse into one another.
    bool seen = false;

    // The last verdict, for GetGuiValue() and LastWasSeparated(). Starts true:
    // the first message to arrive is separated.
    bool separated = true;
  };
}
}
