name: SonarQube
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: false
          install: >-
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-ninja
            mingw-w64-clang-x86_64-portaudio
            mingw-w64-clang-x86_64-libsndfile
            mingw-w64-clang-x86_64-rtmidi
            mingw-w64-clang-x86_64-pkgconf
      - name: Configure CMake
        shell: msys2 {0}
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - name: Run Build Wrapper
        shell: msys2 {0}
        run: |
          build-wrapper-win-x86-64.exe --out-dir "$BUILD_WRAPPER_OUT_DIR" cmake --build build
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define "sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
